// The real general-arrangement plates, and where a frame lands on each one.
//
// Generated by scripts/extract-deck-sheets.py from the prototype's embedded
// copy of the CV-67 Booklet of General Plans. That script is where the
// calibration comes from and why it is per-plate; read its docstring before
// changing any number here.
//
// The important thing this module protects: the plates are NOT drawn to a
// common scale, and they do not share an origin. Using one mapping for all of
// them — which the prototype did — puts a marker up to fifteen frames from the
// compartment it names. On a drawing, fifteen frames is several bulkheads.

import data from "./deckSheets.json";

export interface SheetCalibration {
  /** Sheet pixels per frame. Differs per plate; do not share it. */
  pxPerFrame: number;
  /** Sheet x of frame 0, the forward perpendicular. Frames descend forward. */
  frame0X: number;
  /** Sheet y of the ship's centreline. */
  centrelineY: number;
  halfBeamStep: number;
  /** Half-beam in sheet pixels, sampled every `halfBeamStep` frames from 0. */
  halfBeam: number[];
}

export interface DeckSheet {
  id: string;
  label: string;
  /** The register's deck code, when a plate corresponds to one. */
  deckCode: string | null;
  file: string;
  width: number;
  height: number;
  /** Absent when the plate has no single frame axis — see `deck_island`. */
  calibration: SheetCalibration | null;
}

export const DECK_SHEETS = data.sheets as DeckSheet[];
export const SHEET_SOURCE: string = data.source;
export const SHEET_SOURCE_URL: string = data.sourceUrl;

const BY_DECK = new Map<string, DeckSheet>(
  DECK_SHEETS.filter((s) => s.deckCode !== null).map((s) => [s.deckCode as string, s]),
);

/** The plate for a register deck code, if one has been calibrated for it. */
export function sheetForDeck(deckCode: string | null | undefined): DeckSheet | undefined {
  if (!deckCode) return undefined;
  const sheet = BY_DECK.get(deckCode);
  return sheet?.calibration ? sheet : undefined;
}

/** Sheet x for a frame. */
export function sheetX(cal: SheetCalibration, frame: number): number {
  return cal.frame0X - cal.pxPerFrame * frame;
}

/** Frame at a sheet x — the inverse, for the cursor readout. */
export function sheetFrame(cal: SheetCalibration, x: number): number {
  return Math.round((cal.frame0X - x) / cal.pxPerFrame);
}

/** Half-beam at a frame, linearly interpolated between samples. */
export function halfBeamAt(cal: SheetCalibration, frame: number): number {
  const pos = Math.max(0, frame) / cal.halfBeamStep;
  const i = Math.floor(pos);
  const a = cal.halfBeam[Math.min(i, cal.halfBeam.length - 1)] ?? 0;
  const b = cal.halfBeam[Math.min(i + 1, cal.halfBeam.length - 1)] ?? a;
  return a + (b - a) * (pos - i);
}

/**
 * Sheet y for a compartment's side.
 *
 * The register records *which* side a compartment is on, never how far off the
 * centreline it sits — so this is a legible placement, not a position. It is
 * pinned to a fraction of the local half-beam so a marker stays inside the hull
 * as it narrows toward the bow, and clamped so it stays on the plate even where
 * the measured half-beam is unreliable.
 */
export function sheetY(cal: SheetCalibration, sheet: DeckSheet, side: string, frame: number): number {
  if (side !== "port" && side !== "starboard") return cal.centrelineY;
  const span = Math.min(
    Math.max(0.45 * halfBeamAt(cal, frame), sheet.height * 0.06),
    sheet.height * 0.4,
  );
  return side === "port" ? cal.centrelineY - span : cal.centrelineY + span;
}
