// @generated by `cargo run -p xtask -- gen-leak-tests` — DO NOT EDIT.
// Regenerate after changing `wadl_api::routes::inventory()`; CI runs
// `gen-leak-tests --check` and fails if this file has drifted.
//
// Each test calls a tenant-scoped endpoint AS the yard tenant (assigned to
// every yard hull, so assignment is never the reason) using the NAVY
// tenant's hull id, and asserts not-found. That is the cross-tenant leak
// the row-level-security model must prevent.
#![allow(missing_docs, clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use axum::body::Body;
use axum::http::{Request, StatusCode};
use tower::ServiceExt;

async fn status(method: &str, path: &str, org: &str, assigned: &str) -> StatusCode {
    let (app, _world) = wadl_api::demo_app();
    let request = Request::builder()
        .method(method)
        .uri(path)
        .header("x-org-id", org)
        .header("x-assigned-vessels", assigned)
        .body(Body::empty())
        .unwrap();
    app.oneshot(request).await.unwrap().status()
}

fn yard_assigned(w: &wadl_store::memory::DemoWorld) -> String {
    [w.cvn73, w.cvn71, w.cvn75, w.ddg, w.lpd]
        .iter()
        .map(|v| v.as_uuid().to_string())
        .collect::<Vec<_>>()
        .join(",")
}

#[tokio::test]
async fn leak_get_api_vessels_id() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_compartments() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/compartments"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/compartments must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_work_orders() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/work-orders"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/work-orders must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_stranded_hours() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/stranded-hours"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/stranded-hours must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_compartments_no_state() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/compartments/:no/state"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/compartments/:no/state must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_decks() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/decks"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/decks must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_deck_states() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/deck-states"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/deck-states must be 404"
    );
}

#[tokio::test]
async fn control_in_tenant_get_vessel_is_ok() {
    let (_, w) = wadl_api::demo_app();
    let org = w.navy_org.as_uuid().to_string();
    let assigned = w.navy_hull.as_uuid().to_string();
    let path = format!("/api/vessels/{}", w.navy_hull.as_uuid());
    assert_eq!(status("GET", &path, &org, &assigned).await, StatusCode::OK);
}

#[test]
fn every_scoped_id_route_has_a_leak_test() {
    assert_eq!(wadl_api::routes::scoped_id_routes().len(), 7);
}
