// @generated by `cargo run -p xtask -- gen-leak-tests` — DO NOT EDIT.
// Regenerate after changing `wadl_api::routes::inventory()`; CI runs
// `gen-leak-tests --check` and fails if this file has drifted.
//
// Each test calls a tenant-scoped endpoint AS the yard tenant (assigned to
// every yard hull, so assignment is never the reason) using the NAVY
// tenant's hull id, and asserts not-found. That is the cross-tenant leak
// the row-level-security model must prevent.
#![allow(missing_docs, clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use axum::body::Body;
use axum::http::{Request, StatusCode};
use tower::ServiceExt;

async fn status(
    method: &str,
    path: &str,
    org: &str,
    assigned: &str,
    body: Option<&'static str>,
) -> StatusCode {
    let (app, _world) = wadl_api::demo_app();
    let request = Request::builder()
        .method(method)
        .uri(path)
        .header("x-org-id", org)
        .header("x-assigned-vessels", assigned)
        .header("content-type", "application/json")
        .body(body.map_or_else(Body::empty, Body::from))
        .unwrap();
    app.oneshot(request).await.unwrap().status()
}

fn yard_assigned(w: &wadl_store::memory::DemoWorld) -> String {
    [w.cvn73, w.cvn71, w.cvn75, w.ddg, w.lpd]
        .iter()
        .map(|v| v.as_uuid().to_string())
        .collect::<Vec<_>>()
        .join(",")
}

#[tokio::test]
async fn leak_get_api_vessels_id() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_compartments() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/compartments"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/compartments must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_work_orders() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/work-orders"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/work-orders must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_activities() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/activities"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/activities must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_schedule_alternatives() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/schedule-alternatives"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/schedule-alternatives must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_work_conflicts() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/work-conflicts"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/work-conflicts must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_stranded_hours() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/stranded-hours"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/stranded-hours must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_timeframe() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/timeframe"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/timeframe must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_compartments_no_state() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/compartments/:no/state"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/compartments/:no/state must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_decks() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/decks"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/decks must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_deck_states() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/deck-states"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/deck-states must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_readiness() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/readiness"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/readiness must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_compartments_no_mitigations() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/compartments/:no/mitigations"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/compartments/:no/mitigations must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_leverage() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/leverage"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/leverage must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_issues() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/issues"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/issues must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_issues_acknowledge() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/issues/acknowledge"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status(
        "POST",
        &path,
        &org,
        &assigned,
        Some(r#"{"key":"issue:held:0-000-0-X","note":"leak test"}"#),
    )
    .await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/issues/acknowledge must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_ledger() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/ledger"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/ledger must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_hazards() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/hazards"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/hazards must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_hazards_clear() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/hazards/clear"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status(
        "POST",
        &path,
        &org,
        &assigned,
        Some(r#"{"compartment":"3-148-2-E","kind":"energised_bus","basis":"leak test"}"#),
    )
    .await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/hazards/clear must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_zones() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/zones"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/zones must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_zones() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/zones"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status(
        "POST",
        &path,
        &org,
        &assigned,
        Some(r#"{"label":"leak test","bounds":[{"zone":"Z1","lo_frame":0,"hi_frame":1}]}"#),
    )
    .await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/zones must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_zones_revert() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/zones/revert"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("POST", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/zones/revert must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_budget_book() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/budget-book"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("POST", &path, &org, &assigned, Some(r#"{"label":"leak test","items":[{"code":"WI-0","title":"t","trade":"t","budget_hours":1,"earned_hours":0}]}"#)).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/budget-book must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_budget_book_revert() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/budget-book/revert"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("POST", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/budget-book/revert must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_manning_book() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/manning-book"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/manning-book must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_manning_book() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/manning-book"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status(
        "POST",
        &path,
        &org,
        &assigned,
        Some(r#"{"label":"leak test","crews":[{"trade":"Electrical","headcount":1}]}"#),
    )
    .await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/manning-book must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_manning_book_revert() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/manning-book/revert"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("POST", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/manning-book/revert must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_geometry() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/geometry"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/geometry must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_geometry() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/geometry"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("POST", &path, &org, &assigned, Some(r#"{"label":"leak test","spaces":[{"compartment_no":"3-148-2-E","fwd_frame":148,"aft_frame":152}],"decks":[]}"#)).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/geometry must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_geometry_revert() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/geometry/revert"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("POST", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/geometry/revert must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_schedule_of_record() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/schedule-of-record"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status(
        "POST",
        &path,
        &org,
        &assigned,
        Some(r#"{"label":"leak test","xer":""}"#),
    )
    .await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/schedule-of-record must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_schedule_of_record_revert() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/schedule-of-record/revert"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("POST", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/schedule-of-record/revert must be 404"
    );
}

#[tokio::test]
async fn leak_post_api_vessels_id_compartments_no_decision() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/compartments/:no/decision"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status(
        "POST",
        &path,
        &org,
        &assigned,
        Some(r#"{"disposition":"rejected","option":{},"reason":"leak test"}"#),
    )
    .await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant POST /api/vessels/:id/compartments/:no/decision must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_packages() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/packages"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/packages must be 404"
    );
}

#[tokio::test]
async fn leak_get_api_vessels_id_packages_no() {
    let (_, w) = wadl_api::demo_app();
    let org = w.yard_org.as_uuid().to_string();
    let assigned = yard_assigned(&w);
    let foreign = w.navy_hull.as_uuid().to_string();
    let path = "/api/vessels/:id/packages/:no"
        .replace(":id", &foreign)
        .replace(":no", "4-141-0-C");
    let code = status("GET", &path, &org, &assigned, None).await;
    assert_eq!(
        code,
        StatusCode::NOT_FOUND,
        "cross-tenant GET /api/vessels/:id/packages/:no must be 404"
    );
}

#[tokio::test]
async fn control_in_tenant_get_vessel_is_ok() {
    let (_, w) = wadl_api::demo_app();
    let org = w.navy_org.as_uuid().to_string();
    let assigned = w.navy_hull.as_uuid().to_string();
    let path = format!("/api/vessels/{}", w.navy_hull.as_uuid());
    assert_eq!(
        status("GET", &path, &org, &assigned, None).await,
        StatusCode::OK
    );
}

#[test]
fn every_scoped_id_route_has_a_leak_test() {
    assert_eq!(wadl_api::routes::scoped_id_routes().len(), 35);
}
