//! PostgreSQL-backed reads.
//!
//! These are the real queries behind the tenancy and taxonomy half of
//! [`crate::Repositories`]. Two things about them are load-bearing:
//!
//! * **Every query runs inside a tenant-scoped transaction** ([`PgStore::with_tenant`]),
//!   so row-level security is armed and the tenant filter is the database's job,
//!   not the query's. The SQL below contains no `org_id = $1` clause for that
//!   reason — if a policy were dropped, these queries would start returning other
//!   tenants' rows and the integration test in `tests/pg_rls.rs` would fail. That
//!   is deliberate: the test proves the *policy*, not the query text.
//! * **The assignment gate is applied on top**, because RLS cannot express "this
//!   person is assigned to this hull" (ADR 0003). Tenant isolation and RBAC are
//!   separate gates and are enforced separately.
//!
//! ## What is NOT here yet, and what each one needs
//!
//! Four of the eleven [`crate::Repositories`] methods are still served by
//! [`crate::InMemoryStore`], because moving them requires a decision rather than
//! just a query. Listed so the gap is a known quantity rather than a surprise:
//!
//! * **`live_hazards`** — *the schema has no hazard table.* A hazard is a
//!   derived fact: an open coating ticket, a live hot-work permit, a bus with no
//!   verified zero-energy record. Deriving it means picking which rows constitute
//!   each hazard kind (probably `permit` by `work_type` and status, plus
//!   `space_certificate` expiry), which is a safety-relevant modelling decision
//!   and should be confirmed, not invented.
//! * **`rules_in_force`** — `rule_version.trigger_expr` is `jsonb`, deliberately
//!   "a structured predicate, not code". Nothing yet defines that JSON's shape.
//!   The engine's `Applies::{SameSpace, Coupled}` and its hold minutes are the
//!   de facto schema; writing it down is a small spec, and rules stop being data
//!   in name only once it exists.
//! * **`list_work_orders`** — the model carries one compartment and a budget per
//!   order, but the schema books hours per `work_segment_space`. A non-distributed
//!   order is therefore one segment with one space, and "the order's compartment"
//!   is a roll-up. That is fine, but it means the seed has to create segments for
//!   ordinary work orders too.
//! * **`list_packages` / `get_package` / `stranded_hours`** — these read the same
//!   `work_segment` topology and follow directly once the above is seeded.
//!
//! Two smaller mismatches, visible in this file: [`VesselSummary::confidence`]
//! has no column (it is a planner's judgement, not a stored fact — it may belong
//! in `availability`), and `adjacency_graph` needs `coupling_type.propagates`
//! mapped onto the engine's `Propagation` enum, which is mechanical but wants a
//! rejection path for an unknown value rather than a silent skip.
//!
//! ## Deviation from the stack decision, stated plainly
//!
//! The architecture calls for `query_as!` macros so every statement is verified
//! against the schema at compile time. Those macros need either a live database
//! at build time or an offline cache generated by `sqlx-cli`, and shipping
//! without the cache would break the build for anyone (including CI) without a
//! database. Until `cargo sqlx prepare` is part of the build, these use the
//! runtime-checked `query_as` form, and the integration test exercises each one
//! against a real PostgreSQL so a column rename cannot pass unnoticed.

use sqlx::Row;

use wadl_domain::compartment::CompartmentNo;
use wadl_domain::ids::{OrgId, VesselId};

use crate::error::StoreError;
use crate::model::{CompartmentSummary, DeckSummary, VesselSummary};
use crate::pg::PgStore;
use crate::scope::TenantScope;

/// The demo seed, applied by `wadl seed --database-url`.
pub const SEED_SQL: &str = include_str!("pg_seed.sql");

impl PgStore {
    /// Applies the demo seed. Idempotent, and must run as the table owner: RLS is
    /// enforced for the application role, and a seed able to write across tenants
    /// would defeat the policy it exists to demonstrate.
    ///
    /// # Errors
    /// [`StoreError::Backend`] if any statement fails.
    pub async fn seed_demo(&self) -> Result<(), StoreError> {
        // The seed is many statements; `execute` on a raw multi-statement string
        // runs them in one implicit transaction.
        sqlx::raw_sql(SEED_SQL).execute(self.pool()).await?;
        Ok(())
    }

    /// The hulls visible to `scope`: in-tenant (enforced by RLS) **and** assigned
    /// (enforced here, because a policy cannot express assignment).
    ///
    /// # Errors
    /// [`StoreError::Backend`] on any query failure.
    pub async fn pg_list_vessels(
        &self,
        scope: &TenantScope,
    ) -> Result<Vec<VesselSummary>, StoreError> {
        let mut tx = self.with_tenant(scope.org).await?;
        // No org filter in the SQL: RLS supplies it. The availability picked is
        // the latest by start date — a hull in successive availabilities should
        // show the current one, not an arbitrary row.
        let rows = sqlx::query(
            "SELECT v.vessel_id, v.hull_no, COALESCE(v.name, v.hull_no) AS name,
                    c.code AS class_code,
                    COALESCE(a.code, '—') AS availability_code
               FROM vessel v
               JOIN ship_class c ON c.class_id = v.class_id
               LEFT JOIN LATERAL (
                    SELECT code FROM availability
                     WHERE availability.vessel_id = v.vessel_id
                     ORDER BY start_on DESC NULLS LAST
                     LIMIT 1
               ) a ON TRUE
              ORDER BY v.hull_no",
        )
        .fetch_all(&mut *tx)
        .await?;
        tx.commit().await?;

        Ok(rows
            .into_iter()
            .filter_map(|row| {
                let vessel_id = VesselId::from_uuid(row.get("vessel_id"));
                // The assignment gate. Applied after the query rather than in it
                // so the scope's meaning lives in one place (TenantScope).
                if !scope.is_assigned(vessel_id) {
                    return None;
                }
                Some(VesselSummary {
                    vessel_id,
                    hull_no: row.get("hull_no"),
                    name: row.get("name"),
                    class_code: row.get("class_code"),
                    availability_code: row.get("availability_code"),
                    // Not yet modelled in the schema — see the note in
                    // `Repositories`' PostgreSQL gap list.
                    confidence: "Unknown".to_owned(),
                })
            })
            .collect())
    }

    /// One hull, or [`StoreError::NotFound`] when it is out of tenant or not
    /// assigned. Both refusals return the same error on purpose: distinguishing
    /// them would leak that the row exists.
    ///
    /// # Errors
    /// [`StoreError::NotFound`] when the hull is outside `scope`.
    pub async fn pg_get_vessel(
        &self,
        scope: &TenantScope,
        vessel: VesselId,
    ) -> Result<VesselSummary, StoreError> {
        self.pg_list_vessels(scope)
            .await?
            .into_iter()
            .find(|v| v.vessel_id == vessel)
            .ok_or(StoreError::NotFound)
    }

    /// The hull's decks, ordered downward, with a compartment count per deck.
    ///
    /// # Errors
    /// [`StoreError::NotFound`] when the hull is outside `scope`.
    pub async fn pg_list_decks(
        &self,
        scope: &TenantScope,
        vessel: VesselId,
    ) -> Result<Vec<DeckSummary>, StoreError> {
        // Resolve the hull through the scoped path first, so an out-of-scope hull
        // is refused before any topology is read.
        self.pg_get_vessel(scope, vessel).await?;

        let mut tx = self.with_tenant(scope.org).await?;
        let rows = sqlx::query(
            "SELECT d.code, d.label, d.ordinal, count(cc.class_comp_id) AS compartment_count
               FROM class_deck d
               JOIN vessel v ON v.class_id = d.class_id
               LEFT JOIN class_compartment cc ON cc.deck_id = d.deck_id
              WHERE v.vessel_id = $1
              GROUP BY d.code, d.label, d.ordinal
              ORDER BY d.ordinal",
        )
        .bind(vessel.as_uuid())
        .fetch_all(&mut *tx)
        .await?;
        tx.commit().await?;

        Ok(rows
            .into_iter()
            .map(|row| {
                let count: i64 = row.get("compartment_count");
                DeckSummary {
                    code: row.get("code"),
                    label: row.get("label"),
                    ordinal: row.get("ordinal"),
                    compartment_count: usize::try_from(count).unwrap_or(0),
                }
            })
            .collect())
    }

    /// The compartment register for a hull: the class template, with per-hull
    /// deltas applied. `removed` deltas drop the row; `renamed`/`recategorised`
    /// override the inherited values — class holds the template, hull holds the
    /// truth.
    ///
    /// # Errors
    /// [`StoreError::NotFound`] when the hull is outside `scope`.
    pub async fn pg_list_compartments(
        &self,
        scope: &TenantScope,
        vessel: VesselId,
    ) -> Result<Vec<CompartmentSummary>, StoreError> {
        self.pg_get_vessel(scope, vessel).await?;

        let mut tx = self.with_tenant(scope.org).await?;
        let rows = sqlx::query(
            "WITH delta AS (
                 -- Latest delta per compartment number for this hull.
                 SELECT DISTINCT ON (compartment_no)
                        compartment_no, delta_kind, category, name
                   FROM vessel_compartment
                  WHERE vessel_id = $1
                  ORDER BY compartment_no, effective_from DESC
             )
             SELECT cc.compartment_no,
                    COALESCE(dl.name, cc.name, cc.compartment_no) AS name,
                    COALESCE(d.code, '—')                          AS deck_code,
                    COALESCE(d.ordinal, 0)                         AS ordinal,
                    COALESCE(cc.zone, '—')                         AS zone,
                    COALESCE(dl.category, cc.category, '—')        AS category,
                    -- Cast in SQL: numeric would need a decimal crate for one
                    -- integer frame station, and frames are whole numbers.
                    cc.frame_fwd::int AS frame_fwd,
                    cc.side
               FROM class_compartment cc
               JOIN vessel v            ON v.class_id = cc.class_id
               LEFT JOIN class_deck d   ON d.deck_id  = cc.deck_id
               LEFT JOIN delta dl       ON dl.compartment_no = cc.compartment_no
              WHERE v.vessel_id = $1
                AND (dl.delta_kind IS NULL OR dl.delta_kind <> 'removed')
              ORDER BY COALESCE(d.ordinal, 0), cc.compartment_no",
        )
        .bind(vessel.as_uuid())
        .fetch_all(&mut *tx)
        .await?;
        tx.commit().await?;

        Ok(rows
            .into_iter()
            .map(|row| {
                let compartment_no = CompartmentNo::new(row.get::<String, _>("compartment_no"));
                // The register is authoritative where it carries the geometry.
                // Only fall back to parsing the placard number when it does not
                // — and record which happened, because a parsed position is a
                // convenience for a scheme we understand, not an authored fact.
                let stored_frame: Option<i32> = row.get("frame_fwd");
                let stored_side: Option<String> = row.get("side");
                let parsed = compartment_no.parse_usn();
                let from_register = stored_frame.is_some() && stored_side.is_some();
                CompartmentSummary {
                    frame: stored_frame.or_else(|| parsed.as_ref().map(|u| u.frame.get())),
                    side: stored_side.unwrap_or_else(|| {
                        parsed.as_ref().map_or_else(
                            || "unknown".to_owned(),
                            |u| format!("{:?}", u.side).to_lowercase(),
                        )
                    }),
                    geometry_source: if from_register {
                        "register"
                    } else if parsed.is_some() {
                        "parsed"
                    } else {
                        "unknown"
                    }
                    .to_owned(),
                    compartment_no,
                    name: row.get("name"),
                    deck_code: row.get("deck_code"),
                    deck_ordinal: row.get("ordinal"),
                    zone: row.get("zone"),
                    category: row.get("category"),
                }
            })
            .collect())
    }

    /// Counts the vessel rows RLS exposes to `org`, with **no** assignment
    /// filter. Used by the isolation test to observe the policy directly rather
    /// than inferring it from a filtered result.
    ///
    /// # Errors
    /// [`StoreError::Backend`] on any query failure.
    pub async fn pg_count_visible_vessels(&self, org: OrgId) -> Result<i64, StoreError> {
        let mut tx = self.with_tenant(org).await?;
        let count: i64 = sqlx::query_scalar("SELECT count(*) FROM vessel")
            .fetch_one(&mut *tx)
            .await?;
        tx.commit().await?;
        Ok(count)
    }
}
