//! Repository automation.
//!
//! `gen-leak-tests` is the important one: it reads the API's route inventory
//! (`wadl_api::routes`) and emits one cross-tenant leak test per tenant-scoped,
//! id-addressed endpoint into `crates/wadl-api/tests/generated_leak_test.rs`.
//! Each test calls the endpoint as one tenant with another tenant's id and
//! asserts not-found. Because the tests are generated from the inventory,
//! adding a scoped endpoint to the inventory produces its leak test, and
//! `--check` fails CI if the committed file has drifted from the inventory —
//! which is how an endpoint ends up without a test being a build failure.
//!
//! The same file carries one weakest-role test per gated write route
//! (`wadl_api::roles::GATED`): the request is in-tenant, on an assigned hull,
//! as a `reader`, and must be refused 403 with the route's capability named.
//! A door added to the gate table gets its test; a door left out of the table
//! fails the roles unit test that places every POST.

#![forbid(unsafe_code)]
#![allow(clippy::disallowed_methods)] // xtask is dev tooling, not a library crate

use std::fmt::Write as _;
use std::path::PathBuf;
use std::process::ExitCode;

use anyhow::{bail, Context, Result};
use wadl_api::routes::{self, RouteSpec};

const GENERATED: &str = "crates/wadl-api/tests/generated_leak_test.rs";

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(err) => {
            eprintln!("xtask: {err:#}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<()> {
    let mut args = std::env::args().skip(1);
    match args.next().as_deref() {
        Some("gen-leak-tests") => {
            let check = args.next().as_deref() == Some("--check");
            gen_leak_tests(check)
        }
        Some("gen-ssp") => {
            let check = args.next().as_deref() == Some("--check");
            gen_ssp(check)
        }
        other => bail!("unknown task {other:?}; try: gen-leak-tests [--check] | gen-ssp [--check]"),
    }
}

fn fn_name(spec: &RouteSpec) -> String {
    ident(&format!(
        "leak_{}_{}",
        spec.method.to_ascii_lowercase(),
        spec.path
    ))
}

/// A Rust identifier from a route: non-alphanumerics collapse to one `_`.
fn ident(raw: &str) -> String {
    let mut name = String::with_capacity(raw.len());
    let mut last_underscore = false;
    for ch in raw.chars() {
        if ch.is_ascii_alphanumeric() {
            name.push(ch);
            last_underscore = false;
        } else if !last_underscore {
            name.push('_');
            last_underscore = true;
        }
    }
    name.trim_matches('_').to_owned()
}

fn render() -> String {
    let scoped = routes::scoped_id_routes();
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo run -p xtask -- gen-leak-tests` — DO NOT EDIT.\n\
         // Regenerate after changing `wadl_api::routes::inventory()`; CI runs\n\
         // `gen-leak-tests --check` and fails if this file has drifted.\n\
         //\n\
         // Each leak test calls a tenant-scoped endpoint AS the yard tenant (assigned\n\
         // to every yard hull, so assignment is never the reason) using the NAVY\n\
         // tenant's hull id, and asserts not-found. That is the cross-tenant leak\n\
         // the row-level-security model must prevent.\n\
         //\n\
         // Each weakest-role test calls a gated write route in-tenant, on an\n\
         // assigned hull, as a `reader`, and asserts 403 naming the capability the\n\
         // route needs (`wadl_api::roles::GATED`). That is the least-privilege\n\
         // refusal the role matrix must produce.\n\
         #![allow(missing_docs, clippy::unwrap_used, clippy::expect_used, clippy::panic)]\n\n\
         use axum::body::Body;\n\
         use axum::http::{Request, StatusCode};\n\
         use tower::ServiceExt;\n\n\
         async fn status(\n\
         \x20   method: &str,\n\
         \x20   path: &str,\n\
         \x20   org: &str,\n\
         \x20   assigned: &str,\n\
         \x20   body: Option<&'static str>,\n\
         ) -> StatusCode {\n\
         \x20   let (app, _world) = wadl_api::demo_app();\n\
         \x20   let request = Request::builder()\n\
         \x20       .method(method)\n\
         \x20       .uri(path)\n\
         \x20       .header(\"x-org-id\", org)\n\
         \x20       .header(\"x-assigned-vessels\", assigned)\n\
         \x20       .header(\"content-type\", \"application/json\")\n\
         \x20       .body(body.map_or_else(Body::empty, Body::from))\n\
         \x20       .unwrap();\n\
         \x20   app.oneshot(request).await.unwrap().status()\n\
         }\n\n\
         /// Status and problem body for an in-tenant request as a `reader`.\n\
         async fn as_reader(\n\
         \x20   method: &str,\n\
         \x20   path: &str,\n\
         \x20   org: &str,\n\
         \x20   assigned: &str,\n\
         \x20   body: Option<&'static str>,\n\
         ) -> (StatusCode, serde_json::Value) {\n\
         \x20   let (app, _world) = wadl_api::demo_app();\n\
         \x20   let request = Request::builder()\n\
         \x20       .method(method)\n\
         \x20       .uri(path)\n\
         \x20       .header(\"x-org-id\", org)\n\
         \x20       .header(\"x-assigned-vessels\", assigned)\n\
         \x20       .header(\"x-wadl-person\", \"dev:reader\")\n\
         \x20       .header(\"x-wadl-roles\", \"reader\")\n\
         \x20       .header(\"content-type\", \"application/json\")\n\
         \x20       .body(body.map_or_else(Body::empty, Body::from))\n\
         \x20       .unwrap();\n\
         \x20   let response = app.oneshot(request).await.unwrap();\n\
         \x20   let status = response.status();\n\
         \x20   let bytes = axum::body::to_bytes(response.into_body(), 1 << 20).await.unwrap();\n\
         \x20   (status, serde_json::from_slice(&bytes).unwrap_or(serde_json::Value::Null))\n\
         }\n\n\
         fn yard_assigned(w: &wadl_store::memory::DemoWorld) -> String {\n\
         \x20   [w.cvn73, w.cvn71, w.cvn75, w.ddg, w.lpd]\n\
         \x20       .iter()\n\
         \x20       .map(|v| v.as_uuid().to_string())\n\
         \x20       .collect::<Vec<_>>()\n\
         \x20       .join(\",\")\n\
         }\n\n",
    );

    for spec in &scoped {
        let name = fn_name(spec);
        let _ = write!(
            out,
            "#[tokio::test]\n\
             async fn {name}() {{\n\
             \x20   let (_, w) = wadl_api::demo_app();\n\
             \x20   let org = w.yard_org.as_uuid().to_string();\n\
             \x20   let assigned = yard_assigned(&w);\n\
             \x20   let foreign = w.navy_hull.as_uuid().to_string();\n\
             \x20   let path = \"{path}\".replace(\":id\", &foreign).replace(\":no\", \"4-141-0-C\");\n\
             \x20   let code = status(\"{method}\", &path, &org, &assigned, {body}).await;\n\
             \x20   assert_eq!(code, StatusCode::NOT_FOUND, \"cross-tenant {method} {path} must be 404\");\n\
             }}\n\n",
            name = name,
            path = spec.path,
            method = spec.method,
            body = spec
                .sample_body
                .map_or_else(|| "None".to_owned(), |b| format!("Some(r#\"{b}\"#)")),
        );
    }

    // A control: the same shape of request, in-tenant, must NOT 404 — otherwise
    // the leak assertions could pass simply because the route is broken.
    out.push_str(
        "#[tokio::test]\n\
         async fn control_in_tenant_get_vessel_is_ok() {\n\
         \x20   let (_, w) = wadl_api::demo_app();\n\
         \x20   let org = w.navy_org.as_uuid().to_string();\n\
         \x20   let assigned = w.navy_hull.as_uuid().to_string();\n\
         \x20   let path = format!(\"/api/vessels/{}\", w.navy_hull.as_uuid());\n\
         \x20   assert_eq!(status(\"GET\", &path, &org, &assigned, None).await, StatusCode::OK);\n\
         }\n\n",
    );

    // Coverage: fail if the inventory grew a scoped id-route without regenerating.
    let _ = write!(
        out,
        "#[test]\n\
         fn every_scoped_id_route_has_a_leak_test() {{\n\
         \x20   assert_eq!(wadl_api::routes::scoped_id_routes().len(), {count});\n\
         }}\n\n",
        count = scoped.len(),
    );

    render_weakest_role(&mut out, &scoped);
    out
}

/// The weakest-role block: one 403 test per gated route, plus its count.
fn render_weakest_role(out: &mut String, scoped: &[RouteSpec]) {
    for (method, path, capability) in wadl_api::roles::GATED {
        let name = ident(&format!(
            "weakest_role_{}_{}",
            method.to_ascii_lowercase(),
            path
        ));
        // The sample body from the inventory, so the request reaches the gate
        // the way a real client's would; the gate judges before the body.
        let body = scoped
            .iter()
            .find(|r| r.method == *method && r.path == *path)
            .and_then(|r| r.sample_body)
            .map_or_else(|| "None".to_owned(), |b| format!("Some(r#\"{b}\"#)"));
        let _ = write!(
            out,
            "#[tokio::test]\n\
             async fn {name}() {{\n\
             \x20   let (_, w) = wadl_api::demo_app();\n\
             \x20   let org = w.yard_org.as_uuid().to_string();\n\
             \x20   let assigned = yard_assigned(&w);\n\
             \x20   let hull = w.cvn73.as_uuid().to_string();\n\
             \x20   let path = \"{path}\".replace(\":id\", &hull).replace(\":no\", \"4-141-0-C\");\n\
             \x20   let (code, problem) = as_reader(\"{method}\", &path, &org, &assigned, {body}).await;\n\
             \x20   assert_eq!(code, StatusCode::FORBIDDEN, \"a reader at {method} {path} must be 403\");\n\
             \x20   assert_eq!(problem.get(\"capability\").and_then(serde_json::Value::as_str), Some(\"{cap}\"));\n\
             }}\n\n",
            cap = capability.code(),
        );
    }

    let _ = write!(
        out,
        "#[test]\n\
         fn every_gated_route_has_a_weakest_role_test() {{\n\
         \x20   assert_eq!(wadl_api::roles::GATED.len(), {count});\n\
         }}\n",
        count = wadl_api::roles::GATED.len(),
    );
}

/// Runs the rendered source through `rustfmt` (reading stdin, writing stdout)
/// so the committed file is canonically formatted and `cargo fmt --check`
/// leaves it alone. If `rustfmt` is unavailable, returns the input unchanged —
/// applied identically in both gen and check paths, so the two stay consistent.
fn rustfmt(src: &str) -> String {
    use std::io::Write as _;
    use std::process::{Command, Stdio};

    let child = Command::new("rustfmt")
        .arg("--edition")
        .arg("2021")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn();
    let Ok(mut child) = child else {
        return src.to_owned();
    };
    if let Some(mut stdin) = child.stdin.take() {
        if stdin.write_all(src.as_bytes()).is_err() {
            return src.to_owned();
        }
    }
    match child.wait_with_output() {
        Ok(out) if out.status.success() => {
            String::from_utf8(out.stdout).unwrap_or_else(|_| src.to_owned())
        }
        _ => src.to_owned(),
    }
}

fn gen_leak_tests(check: bool) -> Result<()> {
    let path = PathBuf::from(GENERATED);
    let rendered = rustfmt(&render());
    if check {
        let existing = std::fs::read_to_string(&path)
            .with_context(|| format!("reading {}", path.display()))?;
        if existing != rendered {
            bail!(
                "{} is out of date — run `cargo run -p xtask -- gen-leak-tests`",
                path.display()
            );
        }
        println!(
            "leak tests up to date ({} scoped routes)",
            routes::scoped_id_routes().len()
        );
    } else {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
        std::fs::write(&path, rendered).with_context(|| format!("writing {}", path.display()))?;
        println!(
            "wrote {} ({} scoped routes)",
            path.display(),
            routes::scoped_id_routes().len()
        );
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// gen-ssp: the System Security Plan input document, as a build product.
// ---------------------------------------------------------------------------

const SSP_PATH: &str = "docs/ssp-input.md";

/// Renders `docs/ssp-input.md`. The endpoint inventory and the enforcement
/// parameters are read from the code they describe, so an SSP claim about the
/// API surface cannot drift from the API surface: adding a route changes this
/// document, and CI's `gen-ssp --check` refuses the change until the document
/// is regenerated — the same discipline the leak tests live under.
fn render_ssp() -> String {
    let inventory = routes::inventory();
    let scoped = inventory.iter().filter(|r| r.tenant_scoped).count();
    let open = inventory.len() - scoped;
    let limits = wadl_api::hardening::Limits::default();

    let mut endpoints = String::new();
    for r in &inventory {
        let _ = writeln!(
            endpoints,
            "| `{}` | `{}` | {} |",
            r.method,
            r.path,
            if r.tenant_scoped {
                "tenant-scoped"
            } else {
                "open"
            }
        );
    }

    format!(
        include_str!("ssp_template.md"),
        endpoints = endpoints.trim_end(),
        total = inventory.len(),
        scoped = scoped,
        open = open,
        max_in_flight = limits.max_in_flight,
        timeout_secs = limits.request_timeout.as_secs(),
        import_mb = wadl_api::MAX_IMPORT_BYTES / (1024 * 1024),
    )
}

fn gen_ssp(check: bool) -> Result<()> {
    let path = PathBuf::from(SSP_PATH);
    let rendered = render_ssp();
    if check {
        let existing = std::fs::read_to_string(&path)
            .with_context(|| format!("reading {}", path.display()))?;
        if existing != rendered {
            bail!(
                "{} is out of date — run `cargo run -p xtask -- gen-ssp`",
                path.display()
            );
        }
        println!(
            "SSP input up to date ({} endpoints)",
            routes::inventory().len()
        );
    } else {
        std::fs::write(&path, rendered).with_context(|| format!("writing {}", path.display()))?;
        println!(
            "wrote {} ({} endpoints)",
            path.display(),
            routes::inventory().len()
        );
    }
    Ok(())
}
